name: csth_nutritakes
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  tflite_flutter: ^0.11.0      # Modern TFLite plugin
  camera: ^0.11.1             # Camera access
  image_picker: ^1.0.4          # Gallery access
  http: ^1.1.0                  # API calls (if needed)
  image: ^4.5.4                 # Image processing
  
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt